name: GitHub Actions For Free Pascal Program
on: [push, workflow_dispatch]
jobs:
  GitHub-Actions:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: visualdoj/setup-fpc@main

      - working-directory: ${{ github.workspace }}/src
        run: fpc hello.pas -ohello.exe

      - run: ${{ github.workspace }}/hello.exe
