name: GitHub Actions For Free Pascal Program
on: [push]
jobs:
  GitHub-Actions-Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Installing FPC
        run: sudo apt-get install fpc
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Compiling the program
        run: |
          cd ${{ github.workspace }}/src
          fpc hello.pas
      - name: Running the program
        run: |
          cd ${{ github.workspace }}/src
          ./hello
      - run: echo "🍏 This job's status is ${{ job.status }}."
  GitHub-Actions-Windows:
    runs-on: windows-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Caching Free Pascal Compiler
        uses: actions/cache@v2
        id: cache_fpc_installation_path
        with:
          key: cache_fpc_installation_path
          path: .fpc/release_3_2_2

      - name: Setup Free Pascal Compiler
        if: steps.cache_fpc_installation_path.outputs.cache-hit != 'true'
        uses: visualdoj/setup-fpc@v0.1.11-beta

      # We need this step in case if previous step skipped due to caching
      # Caching cannot be moved to the setup-fpc action because of lack of
      # condition supporting in composite actions
      # See https://github.com/actions/runner/issues/646 for details
      - name: Update PATH
        run: echo ${{ github.workspace }}\.fpc\release_3_2_2\bin\i386-win32 | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: Compiling the program
        working-directory: ${{ github.workspace }}/src
        run: fpc hello.pas

      - name: Running the program
        working-directory: ${{ github.workspace }}/src
        run: .\hello.exe

      - name: List files in the repository
        run: ls ${{ github.workspace }}

      - run: echo "🍏 This job's status is ${{ job.status }}."
