name: GitHub Actions For Free Pascal Program
on: [push]
jobs:
  GitHub-Actions-Linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Installing FPC
        run: sudo apt-get install fpc
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Compiling the program
        run: |
          cd ${{ github.workspace }}/src
          fpc hello.pas
      - name: Running the program
        run: |
          cd ${{ github.workspace }}/src
          ./hello
      - run: echo "🍏 This job's status is ${{ job.status }}."
  GitHub-Actions-Windows:
    runs-on: windows-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Caching Free Pascal Compiler
        uses: actions/cache@v2
        id: cache_fpc_installation
        with:
          path: .fpc/release_3_2_2

      - name: Fetching Free Pascal Compiler
        if: steps.cache_fpc_installation.outputs.cache-hit != 'true'
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "visualdoj/free-pascal-compiler-builds"
          version: "tags/v0.1-alpha"
          file: "release_3_2_2.tar.gz"
          target: ${{ github.workspace }}"/.fpc/release_3_2_2.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unpacking Free Pascal Compiler
        if: steps.cache_fpc_installation.outputs.cache-hit != 'true'
        run: tar -xvzf ${{ github.workspace }}/.fpc/release_3_2_2.tar.gz -C ${{ github.workspace }}/.fpc/release_3_2_2

      - name: Compiling the program
        run: |
          cd ${{ github.workspace }}/src
          ${{ github.workspace }}/.fpc/release_3_2_2/bin/i386-win32/fpc.exe hello.pas

      - name: Running the program
        run: |
          cd ${{ github.workspace }}/src
          hello.exe

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
