name: GitHub Actions For Free Pascal Program
on: [push, workflow_dispatch]
jobs:
  GitHub-Actions:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: visualdoj/setup-fpc@main

      - run: echo ${{ env.PPC_CONFIG_PATH }}

      - run: echo ${{ env.FPC_INSTALLED_DIR }}

      - run: cat  "${{ env.PPC_CONFIG_PATH }}/fpc.cfg"

      - working-directory: ${{ github.workspace }}/src
        run: fpc hello.pas

      - run: ${{ github.workspace }}/src/hello
